### PR TITLE
Prepare RC1

### PR DESCRIPTION
**Pull request by timbussmann**

### CODE REVIEW

**Comment by bording** [comment]
Hmm, a failing test...

**Comment by andreasohlund** [comment]
That was the flaky one that I fixed on develop

https://github.com/Particular/NServiceBus.Callbacks/pull/85

Should we get that fix inte the release branch as well?

**Comment by bording** [comment]
> Should we get that fix inte the release branch as well?

We can go ahead and do a FF merge to get it in there. I'll take care of it.

**Comment by bording** [comment]
@andreasohlund I rebased everything to include your test fix, but the failing test is actually a different test!

**Comment by andreasohlund** [comment]
Hmm, I will take a look tomorrow

**Comment by andreasohlund** [comment]
Found the test issue (same problems as #85)

Raised a PR https://github.com/Particular/NServiceBus.Callbacks/pull/87

**Comment by andreasohlund** [comment]
#87 fixed the failing test, going to merge this

**Pull request merged**
