### PR TITLE
update to latest v6 unstable

### PR DESCRIPTION
**Pull request by timbussmann**
Should we consider moving the callback extension methods to work with `IEndpointInstance` instead of `IMessageSession`?

### CODE REVIEW

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers please review asap

**Comment by andreasohlund** [comment]
My chrystal ball tells me that @danielmarbach proposal for a scoped uow soon will be in scope for v6, Ie all outgoing ops moved away from the endpoint instance. Will this influence this pull?

**Comment by timbussmann** [comment]
well not if we merge it before ;) This PR just adjusts the callbacks to the renamed interfaces and we need to update docs regardless of potential scoped uow.

**Comment by andreasohlund** [comment]
So lets merge as is then?

**Pull request merged**
