### PR TITLE
Removed redundancy in code

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
@timbussmann thanks for the review :dancer:

**Comment by timbussmann** [comment]
code looks good to me :+1: tests run on my machine too, seems to be a build server issue with previously failed messages.

**Comment by danielmarbach** [comment]
I'll pull in latest cleanup changes tomorrow.

**Comment by danielmarbach** [comment]
@timbussmann using latest develop and acceptance test changes now

**Pull request merged**
